import*as THREE from"three";import{PLYLoader}from"three/addons/loaders/PLYLoader.js";import{EffectComposer}from"three/addons/postprocessing/EffectComposer.js";import{RenderPass}from"three/addons/postprocessing/RenderPass.js";import{BokehPass}from"three/addons/postprocessing/BokehPass.js";import{ShaderPass}from"three/addons/postprocessing/ShaderPass.js";import{FXAAShader}from"three/addons/shaders/FXAAShader.js";import{RenderTransitionPass}from"three/addons/postprocessing/RenderTransitionPass.js";import{OutputPass}from"three/addons/postprocessing/OutputPass.js";import{Pass}from"three/addons/postprocessing/Pass.js";import{OBJLoader}from"three/addons/loaders/OBJLoader.js";import{GUI}from"three/addons/libs/lil-gui.module.min.js";import*as TWEEN from"three/addons/libs/tween.module.js";import{OrbitControls}from"three/addons/controls/OrbitControls.js";import{GLTFLoader}from"three/addons/loaders/GLTFLoader.js";let sectionAbout=document.querySelector(".section__about"),phaseList=document.querySelectorAll(".section__about .radio__list input"),camera,scene,renderer,model,material,changingInProgress=!1,textures=["../img/uv_grid_opengl.jpg","../img/Fast-learner.webp","../img/Problem-solving.webp","../img/Ref.png","../img/Research.webp","../img/Team-work.webp","../img/Unwrap.webp"].map(e=>{e=(new THREE.TextureLoader).load(e);return e.colorSpace=THREE.SRGBColorSpace,e}),config={texture1:textures[0],texture2:textures[1],blendFactor:1};function init(){(camera=new THREE.PerspectiveCamera(40,window.innerWidth/window.innerHeight,1,100)).position.set(0,1.65,4.5),(scene=new THREE.Scene).add(new THREE.HemisphereLight(16777215,5592405,1)),(renderer=new THREE.WebGLRenderer({antialias:!0,alpha:!0})).setPixelRatio(devicePixelRatio),renderer.setSize(window.innerWidth,window.innerHeight),renderer.domElement.className="carousel",sectionAbout.insertAdjacentElement("afterbegin",renderer.domElement),(new GLTFLoader).load("../models/Bust.gltf",function(e){(material=new THREE.MeshLambertMaterial({map:textures[0]})).onBeforeCompile=e=>{e.uniforms.map0=material.userData.map0,e.uniforms.mixVal=material.userData.mixVal,e.fragmentShader=`
                uniform sampler2D map0;
                uniform float mixVal;
                ${e.fragmentShader}
            `.replace("#include <map_fragment>",`
                #ifdef USE_MAP
                    vec4 texelColor0 = texture2D( map0, vMapUv );
                    vec4 texelColor1 = texture2D( map, vMapUv );
                    vec4 texelColor = mix(texelColor0, texelColor1, mixVal);
                    diffuseColor *= texelColor;
                #endif
                `)},material.userData={prevIdx:0,map0:{value:textures[0]},mixVal:{value:1}},scene.add(e.scene),e.animations}),onWindowResize(),window.addEventListener("resize",onWindowResize),sectionAbout.addEventListener("wheel",wheelCarousel),renderer.setAnimationLoop(animate)}function onWindowResize(){renderer.setPixelRatio(devicePixelRatio),renderer.setSize(window.innerWidth,window.innerHeight)}function animate(){scene.children[1]&&(scene.children[1].rotation.y+=.002),TWEEN.update(),renderer.render(scene,camera)}function changeTexture(e){!0!==changingInProgress&&(material.map=textures[e],material.userData.map0.value=textures[material.userData.prevIdx],material.userData.prevIdx=e,material.userData.mixVal.value=0,new TWEEN.Tween(material.userData.mixVal).to({value:1},1e3).onStart(()=>{changingInProgress=!0}).onComplete(()=>{changingInProgress=!1}).start())}function wheelCarousel(e){scene.children[1].rotation.y+=.002*-e.deltaX}init(),Array.from(phaseList).forEach(e=>{e.addEventListener("input",e=>{changeTexture(e.target.defaultValue)})});